{
 "title": "Nacos",
 "description": "Nacos grafana dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "集群",
    "query": {
     "query": "label_values(nacos_monitor,job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(nacos_monitor{job=~\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "nacos monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "UP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(nacos_monitor{name=\"configCount\",job=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "service count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(nacos_monitor{name='serviceCount',job=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "ip count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(nacos_monitor{name='ipCount',job=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "config count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(nacos_monitor{name='configCount', job=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "long polling",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='longPolling'})"
    }
   ]
  },
  {
   "title": "config push total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='getConfig', instance=~'$instance'}) by (name)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "options": {
    "content": "<center>\n  <a href=\"https://nacos.io\">\n    <img src=\"https://s1.ax1x.com/2020/10/22/BiuZRO.png\" style=\"height: 50px; margin-top:20px\" />\n  </a>\n</center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "cpu alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(process_cpu_usage{instance=~'$instance'}) * 1000"
    }
   ]
  },
  {
   "title": "memory alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\",instance=~'$instance'})/sum(jvm_memory_max_bytes{area=\"heap\",instance=~'$instance'}) * 100"
    }
   ]
  },
  {
   "title": "alert list",
   "type": "alertlist",
   "gridPos": { "h": 15, "w": 6, "x": 18, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "threads alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(jvm_threads_daemon_threads{instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "qps",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=~'$instance'}[1m]))"
    }
   ]
  },
  {
   "title": "rt alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{instance=~'$instance'}[1m]))/sum(rate(http_server_requests_seconds_count{instance=~'$instance'}[1m])) * 1000"
    }
   ]
  },
  {
   "title": "long polling",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 14 },
   "repeat": "group",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='longPolling', instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "nacos detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "qps",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=~'root|/v1/ns/instance/list|/v1/ns/instance/beat', instance=~'$instance'}[1m])) by (method,uri)"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=~'$instance'}[1m]))"
    }
   ]
  },
  {
   "title": "rt",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{uri=~'root|/v1/ns/instance/list|/v1/ns/instance/beat', instance=~'$instance'}[1m])/rate(http_server_requests_seconds_count{uri=~'root|/v1/ns/instance/list|/v1/ns/instance/beat', instance=~'$instance'}[1m])) by (method,uri) * 1000"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{instance=~'$instance'}[1m]))/sum(rate(http_server_requests_seconds_count{instance=~'$instance'}[1m])) * 1000",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "gc alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(jvm_gc_pause_seconds_count{action=\"end of major GC\",instance=~'$instance'}[5m])) * 300"
    }
   ]
  },
  {
   "title": "health check",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacos_monitor{name=~'.*HealthCheck', instance=~'$instance'}[1m])) by (name) * 60"
    }
   ]
  },
  {
   "title": "load 1m",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(system_load_average_1m{instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "leaderStatus",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nacos_monitor{name=\"leaderStatus\",job=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "config statistics",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='publish', instance=~'$instance'}) by (name)",
     "legendFormat": "publish config"
    },
    {
     "expr": "sum(nacos_monitor{name='getConfig', instance=~'$instance'}) by (name)",
     "legendFormat": "get config"
    }
   ]
  },
  {
   "title": "notify rt",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacos_timer_seconds_sum{instance=~'$instance'}[1m]))/sum(rate(nacos_timer_seconds_count{instance=~'$instance'}[1m])) * 1000"
    }
   ]
  },
  {
   "title": "avgPushCost",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='avgPushCost', instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "nacos alert",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "db exception alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacos_exception_total{name='db'}[1m])) * 60"
    }
   ]
  },
  {
   "title": "load  alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "max(system_load_average_1m)" }
   ]
  },
  {
   "title": "notify task alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='notifyTask'})"
    }
   ]
  },
  {
   "title": "naming disk exception alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacos_exception_total{name=\"disk\",job=\"$cluster\"}[1m])) * 60"
    }
   ]
  },
  {
   "title": "long polling alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(nacos_monitor{name='longPolling'})"
    }
   ]
  },
  {
   "title": "config unhealth exception alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacos_exception_total{name=\"unhealth\",job=\"$cluster\"}[1m])) * 60"
    }
   ]
  },
  {
   "title": "nacos exception alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacos_exception_total{name=\"nacos\",job=\"$cluster\"}[1m])) * 60"
    }
   ]
  },
  {
   "title": "maxPushCost",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(nacos_monitor{name='maxPushCost', instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "illegalArgument exception alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacos_exception_total{name='illegalArgument'}[1m])) * 60"
    }
   ]
  },
  {
   "title": "config notify exception alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacos_exception_total{name='configNotify'}[1m])) * 60"
    }
   ]
  },
  {
   "title": "failed push alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nacos_monitor{name=\"failedPush\",job=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "naming leader send beat failed exception alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacos_exception_total{name=\"leaderSendBeatFailed\",job=\"$cluster\"}[1m])) * 60"
    }
   ]
  }
 ]
}